id: P000509
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:43:37.629445
source_metadata:
  id: bdr:W1PD181172
  title: གཡག་ཟེའི་སྐུ་ཆུང་ལྔ་པ་གར་དབང་བསྟན་འཛིན་བཟང་པོའི་གཏེར་ཆོས།
  author: ''
  volumes:
    ef01c7c8182b49d7baa1d3a254406245:
      image_group_id: I4CZ74477
      title: Volume 1 of sku 'bum gdan rabs/
      volume_number: 1
      total_pages: 620
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
